# Form implementation generated from reading ui file 'createScript.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(362, 328)
        self.name_line = QtWidgets.QLineEdit(parent=Dialog)
        self.name_line.setGeometry(QtCore.QRect(10, 10, 341, 20))
        self.name_line.setObjectName("name_line")
        self.start_button = QtWidgets.QPushButton(parent=Dialog)
        self.start_button.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.start_button.setObjectName("start_button")
        self.list = QtWidgets.QListWidget(parent=Dialog)
        self.list.setGeometry(QtCore.QRect(10, 40, 341, 241))
        self.list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.list.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.list.setObjectName("list")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_button.setText(_translate("Dialog", "START"))
